# Generated by Django 6.0.6 on 2026-06-17 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systempermission_userpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ollama_host', models.CharField(default='localhost', max_length=255, verbose_name='آدرس Host')),
                ('ollama_port', models.IntegerField(default=11434, verbose_name='پورت')),
                ('ollama_model', models.CharField(default='gemma3:27b', max_length=100, verbose_name='مدل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('timeout_seconds', models.IntegerField(default=120, verbose_name='زمان انتظار (ثانیه)')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='حداکثر توکن\u200cها')),
                ('temperature', models.FloatField(default=0.3, verbose_name='دمای خلاقیت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تنظیمات هوش مصنوعی',
                'verbose_name_plural': 'تنظیمات هوش مصنوعی',
            },
        ),
    ]
