# Generated by Django 6.0.6 on 2026-06-19 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aisettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='', max_length=255, verbose_name='IP Address')),
                ('subnet_mask', models.CharField(blank=True, default='', max_length=255, verbose_name='Subnet Mask')),
                ('default_gateway', models.CharField(blank=True, default='', max_length=255, verbose_name='Default Gateway')),
                ('primary_dns', models.CharField(blank=True, default='', max_length=255, verbose_name='Primary DNS')),
                ('secondary_dns', models.CharField(blank=True, default='', max_length=255, verbose_name='Secondary DNS')),
                ('server_ip', models.CharField(default='127.0.0.1', max_length=255, verbose_name='Server IP')),
                ('server_port', models.IntegerField(default=8000, verbose_name='Server Port')),
                ('allow_remote_access', models.BooleanField(default=False, verbose_name='Allow Remote Access')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
    ]
