# Generated by Django 6.0.6 on 2026-06-21 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AINotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('notification_type', models.CharField(choices=[('file_analysis', 'تحلیل فایل'), ('threat_detected', 'تهدید شناسایی شده'), ('user_analysis', 'تحلیل کاربر'), ('system_alert', 'هشدار سیستمی')], default='file_analysis', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'اطلاعاتی'), ('warning', 'هشدار'), ('critical', 'بحرانی')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('unread', 'خوانده نشده'), ('read', 'خوانده شده'), ('resolved', 'رسیدگی شده')], default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.uploadedfile')),
                ('target_users', models.ManyToManyField(blank=True, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوتیفیکیشن AI',
                'verbose_name_plural': 'نوتیفیکیشن\u200cهای AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
