# Generated by Django 6.0.6 on 2026-06-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ainotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileactionlog',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='تحلیل AI'),
        ),
        migrations.AddField(
            model_name='fileactionlog',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه AI'),
        ),
        migrations.AddField(
            model_name='fileactionlog',
            name='is_threat',
            field=models.BooleanField(default=False, verbose_name='تهدید است؟'),
        ),
        migrations.AddField(
            model_name='fileactionlog',
            name='threat_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='سطح تهدید'),
        ),
    ]
